config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token, :reset_token
	before_save :downcase_email
	before_create :create_activation_digest
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true
	has_secure_password

	class << self
		# Returns the hash digest of the given string.
		def digest(string)
		  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		                                                BCrypt::Engine.cost
		  BCrypt::Password.create(string, cost: cost)
		end

		# Returns a random token.
		def new_token
		  SecureRandom.urlsafe_base64
		end
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def activate
		update_columns(activated: true, activated_at: Time.zone.now)
	end

	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	def create_reset_digest
		self.reset_token = User.new_token
	    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
	end

	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end

	def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end

	private

		def downcase_email
			self.email.downcase!
		end

		def create_activation_digest
			self.activation_token=User.new_token
			self.activation_digest=User.digest(activation_token)
		end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

	def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = "Account activated!"
      redirect_to user
    else
      flash[:danger] = "Invalid activation link"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
  	@user=User.find_by(email: params[:password_reset][:email].downcase)
  	if @user
  		@user.create_reset_digest
  		@user.send_password_reset_email
  		flash[:info]="Email sent with password reset instructions"
  		redirect_to root_url
  	else
  		flash.now[:danger]="Email address not found"
  		render 'new'
  	end
  end

  def edit
  end

  def update
  	if params[:user][:password].empty?
  		@user.errors.add(:password, "can't be empty")
  		render 'edit'
  	elsif @user.update_attributes(user_params)
  		log_in(@user)
  		@user.update_attribute(:reset_digest, nil)
  		flash[:success]="Password has been reset."
  		redirect_to @user
  	else
  		render 'edit'
  	end
  end

  private

  	def get_user
  		@user=User.find_by(email: params[:email])
  	end

  	def user_params
  		params.require(:user).permit(:password, :password_confirmation)
  	end

  	def valid_user
  		unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
  			redirect_to root_url
  		end
  	end

  	def check_expiration
  		if @user.password_reset_expired?
  			redirect_to new_password_reset_url
  		end
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user=User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
		if user.activated?
			log_in user
			params[:session][:remember_me] == '1' ? remember(user) : forget(user)
			redirect_back_or user
		else
			message  = "Account not activated. "
			message += "Check your email for the activation link."
			flash[:warning] = message
			redirect_to root_url
		end
  	else
  		flash.now[:danger]="Invalid email/password combination"
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about  	
  end

  def contact
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def new
  	@user=User.new
  end

  def index
  	@users = User.where(activated: true).paginate(page: params[:page])
  end

  def destroy
  	User.find(params[:id]).destroy
  	flash[:success]="User deleted!"
  	redirect_to users_url
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		@user.send_activation_email
  		flash[:info]="Please check your email to activate your account."
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def show
  	@user=User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
  end

  def edit
  	@user=User.find(params[:id])
  end

  def update
  	@user=User.find(params[:id])
  	if @user.update_attributes(user_params)
  		flash[:success]="Profile updated!"
  		redirect_to @user
  	else
  		render 'edit'
  	end
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

  	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger]="Please Log in first."
			redirect_to login_url
		end
	end

	def correct_user
		@user=User.find(params[:id])
		redirect_to(root_url) unless current_user?(@user)
	end

	def admin_user
		redirect_to(root_url) unless current_user.admin?
	end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title='')
		base_title="Majestic Ads"
		if page_title.empty?
			base_title
		else
			page_title + ' | ' + base_title
		end
	end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if (user_id=session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id=cookies.signed[:user_id])
			user=User.find_by(id: user_id)
			if user && user.authenticated?(:remember, cookies[:remember_token])
				log_in user
				@current_user=user
			end
		end
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user=nil
	end

	def logged_in?
		!current_user.nil?
	end

	def current_user?(user)
		user==current_user
	end

	def store_location
		session[:forwarding_url]=request.original_url if request.get?
	end

	def redirect_back_or(default)
		redirect_to(session[:forwarding_url]||default)
		session.delete(:forwarding_url)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options={size: 80})
		gravatar_id=Digest::MD5::hexdigest(user.email.downcase)
		size=options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top">
    <div class="container">
      <div>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" onclick="openNav()">
          <span style="background-color: #fff;" class="icon-bar"></span>
          <span style="background-color: #fff;" class="icon-bar"></span>
          <span style="background-color: #fff;" class="icon-bar"></span> 
        </button>
        <%= link_to "Majestic Ads", root_path, id: "logo" %>
      </div>
      <div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "Help",   help_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropbtn">
                <%= gravatar_for current_user, size: 30 %> <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-content">
                <li><%= link_to '<i class="fa fa-user"></i> Profile'.html_safe, current_user %></li>
                <li><%= link_to '<i class="fa fa-cog"></i> Settings'.html_safe, edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to '<i class="fa fa-sign-out"></i> Log out'.html_safe, logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li id="log_in"><a href="/login"><i id="login" class="fa fa-sign-in"></i> Log in</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

<div id="myNav" class="overlay">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times</a>
  <div class="overlay-content">
    <%= link_to "Home",   root_path %>
    <%= link_to "Help",   help_path %>
    <% if logged_in? %>
      <%= link_to "Users", users_path %>
      <%= link_to '<i class="fa fa-user"></i> Profile'.html_safe, current_user %>
      <%= link_to '<i class="fa fa-cog"></i> Settings'.html_safe, edit_user_path(current_user) %>
      <%= link_to '<i class="fa fa-sign-out"></i> Log out'.html_safe, logout_path, method: "delete" %>
    <% else %>
      <a href="/login"><i id="login" class="fa fa-sign-in"></i> Log in</a>
    <% end %>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="author" content="Rishabh Khatri">
    <meta name="description" content="Ruby on Rails Sample App">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:100' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Abril+Fatface' rel='stylesheet' type='text/css'>
    <!-- Font awesome -->
    <script src="https://use.fontawesome.com/220eb7c274.js"></script>
    <!-- Google Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!-- Smooth Scroll -->
    <script>
    $(document).ready(function(){
      $("a").on('click', function(event) {
        if (this.hash !== "") {
          event.preventDefault();
          var hash = this.hash;
          $('html, body').animate({
            scrollTop: $(hash).offset().top
          }, 600, function(){
            window.location.hash = hash;
          });
        }
      });
    });
    </script>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      	<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<% provide(:title, "Password reset") %>
<h1>Password reset</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
		<%= render 'shared/error_messages' %>

		<%= hidden_field_tag :email, @user.email %>

		<%= f.label :password %>
		<%= f.password_field :password, class: 'form-control' %>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation, class: 'form-control' %>

		<%= f.submit "Update password", class: "btn btn-primary" %>
	<% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<%= provide(:title, "Forgot password") %>

<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p style="font-size: 20px;">
  <a style="text-decoration: none;" href="http://esya.iiitd.edu.in" target="_blank" rel="noopener">Esya</a> presents its first ever ad making competition <a style="text-decoration: none;" href="/">Majestic Ads</a>. It will be an online event. Contestants will be asked to prepare short ads,animation videos or any type of video on any one of the given themes, the themes would be provided after they fill the registration form. The videos will be judged on the basis of quality, content and incorporation of the themes in the ads and YouTube likes as well.
</p>

<p style="font-size: 20px;">
	To know more about Majestic Ads and <a style="text-decoration: none;" href="http://esya.iiitd.edu.in" target="_blank" rel="noopener">Esya</a> visit the facebook <a style="text-decoration: none;" href="https://www.facebook.com/events/623205334504592/">page</a>.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p style="font-size: 20px">
  Contact us at our facebook <a style="text-decoration: none;" href="https://www.facebook.com/events/623205334504592/">page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p style="font-size: 20px;">
	To know more about Majestic Ads and <a style="text-decoration: none;" href="http://esya.iiitd.edu.in" target="_blank" rel="noopener">Esya</a> visit the facebook <a style="text-decoration: none;" href="https://www.facebook.com/events/623205334504592/">page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>Welcome to Majestic Ads</h1>
  <% if !logged_in? %>
	  <h2 style="font-size: 20px;">
	    Welcome to the Majestic Ads home page. Signup now to stand a chance to win exciting prizes!
	  </h2>
  	<%= link_to '<i class="fa fa-user-plus fa-inverse"></i> Register now!'.html_safe, signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) && !user.admin? %>
		<span style="font-size: 20px;"> | </span><%= link_to "delete", user, method: :delete, data:{confirm: "You sure?"} %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <br>
      <button class="btn btn-primary"><a style="text-decoration: none; font-family: roboto, sans-serif; font-size: 17px; color: #fff;" href="http://gravatar.com/emails" rel="noopener" target="_blank">Change</a></button>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>